package sql_connection;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo Ruiz Rios
 */
public class CustomerQuery extends javax.swing.JInternalFrame {

    DefaultTableModel dtm;
    Object data[] = new Object[5];

    BD_Connection ctr = new BD_Connection();

    /**
     * Creates new form CustomerQuery
     */
    public CustomerQuery() {
        initComponents();
        dtm = (DefaultTableModel) jTable1.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customer_query_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        customer_query_btn.setText("Consutla");
        customer_query_btn.setToolTipText("Execute the query to retrieve Customer Info");
        customer_query_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customer_query_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_query_btnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Cliente", "Nombre_Cliente", "ApellidoP", "ApellidoM", "Observaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Info de Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(customer_query_btn)
                        .addGap(207, 207, 207))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customer_query_btn)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customer_query_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_query_btnActionPerformed
        // TODO add your handling code here:

        int row_count = jTable1.getRowCount();

        if (row_count > 0) {
            dtm.setRowCount(0);
        }

        try {
            ctr.setConnection();
            ctr.createStmt();

            if (ctr.runQuery(String.format("SELECT * FROM clientes"))) {
                if (ctr.getRS().next()) {

                    do {
                        data[0] = ctr.getInt(1);
                        data[1] = ctr.getString(2);
                        data[2] = ctr.getString(3);
                        data[3] = ctr.getString(4);
                        data[4] = ctr.getString(5);
                        dtm.addRow(data);
                    } while (ctr.getRS().next());
                } else {
                    JOptionPane.showMessageDialog(null, "La tabla clientes está vacía", "Tabla vacía", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(SQL_Connection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ERROR: no se pudo ejecutar la consulta.", "Error de Conexión", JOptionPane.ERROR_MESSAGE);
        } finally {
            ctr.closeRS();
            ctr.disconnect();
        }
    }//GEN-LAST:event_customer_query_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customer_query_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
